### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by cmacmackin** [thomasms/peakingduck#11]
I notice that at least Python 3.7 is supported. This is quite a recent version; Ubuntu 18.04 only comes with 3.6.9. Is there any particular reason you need 3.7 and that 3.6 wouldn't work?

**Comment by cmacmackin** [comment]
I tried building with 3.6.9 on my PC running Ubuntu 18.04 (bionic) and it all seemed to work. I'd suggest requiring only this version.

**Comment by thomasms** [comment]
Sure 3.6 is fine to support.
