### ISSUE TITLE
Docstrings for the Python interface

### ISSUE THREAD

**Issue by cmacmackin** [thomasms/peakingduck#15]
Passing docstrings to Pybind ensures they will be available from within the Python REPL and from Sphinx-generated documentation. However, many of the C++ functions are already documented in Doxygen format in their source files and it is useful to have this documentation adjacent to the implementation. In order to avoid repeating ourselves or different versions of the docs becoming out of sync, I tried using the [mkdoc script](https://github.com/pybind/pybind11/blob/master/tools/mkdoc.py) distributed with Pybind. This produces header files with static variables containing docstrings parsed from Doxygen comments. These can be generated as part of the build system and then be passed to PyBind.

Unfortunately, the `mkdoc.py` script depends on `libclang` to work, which is not installed by default on most systems. I'd prefer not to introduce this somewhat obscure library as a build-dependency, so options include:

- provide a fallback header file containing empty docstrings, so can compile without libclang
- use mkdoc to generate docstrings the first time and then manually ensure they stay in sync
- declare Python docstrings adjacent to the C++ functions, so they can still function as in-line documentation (though would not be compatible with Doxygen)
- go back to manually maintaining completely separate sets of documentation
- modify mkdoc to remove libclang dependency (unknown difficulty)

**Comment by thomasms** [comment]
I am open to all options other than the last. In your opinion, what do you think is the best solution?

Two different types of documentation are not ideal but better than no documentation. It would be painful to copy and paste documentation to two different syntaxes but still better than requiring libclang as a dependency. What would option 3 involve exactly? Can you give a code snippet example?

We could also just ignore docstring and have specific dedicated builds for building a version with docstring. Since most users will likely just pip install anyway, as long as we ensure that that version has correct doc we should be OK.

**Comment by cmacmackin** [comment]
I would suggest either option 1 or 3. Option 1 would integrate nicely with what you suggest in your final paragraph. Option 3 could look something like the following:
```c++
    template<typename ValueType=DefaultType>
    struct PeakInfo
    {
        static constexpr string docstring =  
R"doc(Simple struct for holding peak info.

Attributes:
    value: value, i.e. count or flux.
    index: the corresponding index/channel of the data.
)doc";
        const size_t index;
        const ValueType value;

        PeakInfo(size_t pindex, ValueType pvalue) : index(pindex), value(pvalue) {}
    };
```

Here I've used the [Google style](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) for Python docstrings. Alternatively, I could declare the docstring outside of the scope of the class, so that it could be easily optimised out when using the header-only library, at a slight cost of readability.

**Comment by thomasms** [comment]
Option 3 looks OK, I could live with that. 
With option 1 if most people don't have libclang then there would be no documentation - correct?

**Comment by cmacmackin** [comment]
With option 1 it depends how they install it. If we were to compile the PEAKINGDUCK.so file before uploading it to PyPI then we could make sure it is done on a machine with libclang (e.g. the CI server) and then those installing it would have access to the documentation.

That said, the more I think about it the less I like the script used to generate Python docs from the C++ ones. It is rather flaky and I would almost certainly have to make some edits to it and distribute our own version. However, if I do that then I could simltaneously generate separate C++ and Python API documentation, using Doxygen/[Breathe](https://breathe.readthedocs.io/en/latest/) and sphinx-autodoc respectively.

If we were to go with the approach of writing docstring variables in C++, on the other hand, then generating documentation for the C++ API would be much more difficult. The best way to do it would probably be to write a simple program which would print out the values of the docstrings, with additional headings so that Sphinx could process it (see example below). This wouldn't be difficult but the lack of introspection in C++ means it would be slightly tedious and would have to be continually maintained.

```C++
#include <iostream>
#include <peakingduck.hpp>

string indent(const string &docs, int n) {
    // Some code to indent each line of `docs` by `n` spaces
}

void main() {
    std::cout << ".. cpp:struct:: template<typename Valuetype=DefaultType> PeakInfo\n\n";
    std::cout << indent(PeakInfo::docstring) << "\n";
    // Plus similar for any methods I wish to document
}
```

**Comment by thomasms** [comment]
This all seems a bit messy. Let's take Occam's razor approach and just maintain two sets of documentation. C++ is already documented (well mostly). Let's just copy this to docstrings.
Every time a user adds a new algorithm in python, it's just one layer of doc, if they do it in C++, then it is twice. I am hoping once the core algorithms are ported into C++ then we can just assume most of the new stuff will be python anyway.

Please feel free to shoot me down if this is crazy talk, but it seems like all this effort and the associated dependencies will cause problems later.

**Comment by cmacmackin** [comment]
Frankly, there is no ideal solution to this and there isn't a clear choice. Maintaining two sets works about as well as anything. It does have the additional advantage that we can customise documentation to peculiarities of each language as needed. Specifically, docs for the C++ code can discuss templates while those for Python would refer specifically to floats and ints as the data-type.

**Comment by cmacmackin** [comment]
I've added separate docstrings for the Pybind interface, reformatting them to work with Sphinx. They could likely use some further changes and elaboration, but that is for another time.
