### ISSUE TITLE
Organising C++ API documentation

### ISSUE THREAD

**Issue by cmacmackin** [thomasms/peakingduck#16]
I'm currently in the process of integrating Doxygen output with Sphinx using the [Breathe](https://breathe.readthedocs.io/en/latest/) plugin. I'm wondering how best to organise this documentation. For the Python API docs I organised them into pages based which module they must be imported from in Python (e.g., `peakingduck.core`, `peakingduck.io`, etc.). However, this becomes a bit more complicated in C++, as the closets equivalent to a module (namespaces) does not have a 1-to-1 mapping with source files. I'm currently leaning towards organising documentation along namespaces as this would be more useful to anyone who wishes to use the header only library. However, organising it along source files could be more useful for those wishing to do development. Do you have a preference?

**Comment by thomasms** [comment]
I have no preference. Whatever makes your life easier.

**Comment by cmacmackin** [comment]
I've got the docs building on Read the Docs: https://peakingduck.readthedocs.io/en/develop/. Currently, only the development branch is showing, as the configurations have not be merged into master yet.

**Comment by thomasms** [comment]
Nice work. That looks really good, thanks for going through the pain to set this up.
