### ISSUE TITLE
Reason for wrapping namespace declaration?

### ISSUE THREAD

**Issue by cmacmackin** [thomasms/peakingduck#17]
I notice that rather than just declaring namespaces in the C++ headers, a macro is written to do this? What is the reason for this. Unfortunately it seems to be preventing Doxygen from picking up on the namespace declarations (although I may be able to fix this with further configuration).

**Comment by thomasms** [comment]
The only reason is readability. I find using namespaces and the matching curly brackets a pain to use, especially when you have many namespaces.

```cpp
namespace first{
namespace second{
namespace third{

// ...
    void myfunc(){
       //...

    // I don't like these brackets
    }
}
}
}
```

```cpp
PEAKINGDUCK_NAMESPACE_START(first)
PEAKINGDUCK_NAMESPACE_START(second)
PEAKINGDUCK_NAMESPACE_START(third)

// ...
    void myfunc(){
       //...

    // brackets are clearer
    }
PEAKINGDUCK_NAMESPACE_END
PEAKINGDUCK_NAMESPACE_END
PEAKINGDUCK_NAMESPACE_END
```

It doesn't really matter, it's just readability mainly. If you want to get rid of them for documentation purposes, I guess this would be OK.

**Comment by cmacmackin** [comment]
I can't seem to figure out how to get Doxygen to correctly process these macros and I think it is important that the docs contain information on namespaces. As such I've opted to do away with the macros. I will add comments on closing curly braces to make it clear that they are ending a namespace.

```cpp
namespace first{
namespace second{
namespace third{

// ...
    void myfunc(){
       //...

    // I don't like these brackets
    }
} // namespace third
} // namespace second
} // namespace first
```
That should help with readability somewhat.

**Comment by cmacmackin** [comment]
Actually, nevermind. In the course of fixing another problem I figured out how to get Doxygen to parse this properly. I'll restore your use of the macros.
