### ISSUE TITLE
Set up webhook for Read The Docs

### ISSUE THREAD

**Issue by cmacmackin** [thomasms/peakingduck#18]
I'm setting up a Read The Docs site for this project. I have linked it to this repository, but in order for it to automatically rebuild documentation whenever there is a new push the repository owner will need to configure a webhook. Thomas, could you please do this using [the instructions provided by RTD](https://docs.readthedocs.io/en/stable/webhooks.html#github)? The "Payload URL" is `https://readthedocs.org/api/v2/webhook/peakingduck/113796/`.

**Comment by thomasms** [comment]
OK - should be done. Let me know otherwise.

**Comment by cmacmackin** [comment]
That seems to be working.

I'd like to add you as a maintainer on Read the Docs. Would you mind creating an account there and letting me know your username? Thanks.

**Comment by thomasms** [comment]
Username is the same as GitHub - thomasms
